using AdeyanjuApplication.Entities.DbSet;
using AdeyanjuApplication.Entities.DTO.Request;
using AutoMapper;
using ChurchApplication.Entities.DTO.Request;

namespace AdeyanjuApplication.API.MappingProfile
{
    public class RequestToDomain : Profile
    {
        public RequestToDomain()
        {
            CreateMap<CreatePastor, Pastor>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => Guid.NewGuid().ToString()))
                .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName))
                .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName))
                .ForMember(dest => dest.ChurchAddress, opt => opt.MapFrom(src => src.ChurchAddress))
                .ForMember(dest => dest.HomeAddress, opt => opt.MapFrom(src => src.HomeAddress))
                .ForMember(dest => dest.YearsInService, opt => opt.MapFrom(src => src.YearsInService))
                .ForMember(dest => dest.PhoneNumber, opt => opt.MapFrom(src => src.PhoneNumber))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.EmailAddress))
                .ForMember(dest => dest.Occupation, opt => opt.MapFrom(src => src.Occupation))
                .ForMember(dest => dest.BranchName, opt => opt.MapFrom(src => src.BranchName))
                .ForMember(dest => dest.Occupation, opt => opt.MapFrom(src => src.Occupation))
                .ForMember(dest => dest.StateOfOrigin, opt => opt.MapFrom(src => src.StateOfOrigin))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => 1))
                .ForMember(dest => dest.DateOfBirth, opt => opt.MapFrom(src => src.DateOfBirth))
                .ForMember(dest => dest.Created, opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.Updated, opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
                .ForMember(dest => dest.UserRoleId, opt => opt.MapFrom(src => src.Role))
                .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Gender));

            CreateMap<UpdatePastor, Pastor>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName)) 
                .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName))
                .ForMember(dest => dest.ChurchAddress, opt => opt.MapFrom(src => src.ChurchAddress))
                .ForMember(dest => dest.HomeAddress, opt => opt.MapFrom(src => src.HomeAddress))
                .ForMember(dest => dest.YearsInService, opt => opt.MapFrom(src => src.YearsInService))
                .ForMember(dest => dest.PhoneNumber, opt => opt.MapFrom(src => src.PhoneNumber))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.EmailAddress))
                .ForMember(dest => dest.EmailConfirmed, opt => opt.MapFrom(src => src.EmailAddress.ToUpper()))
                .ForMember(dest => dest.Occupation, opt => opt.MapFrom(src => src.Occupation))
                .ForMember(dest => dest.BranchName, opt => opt.MapFrom(src => src.BranchName))
                .ForMember(dest => dest.Occupation, opt => opt.MapFrom(src => src.Occupation))
                .ForMember(dest => dest.StateOfOrigin, opt => opt.MapFrom(src => src.StateOfOrigin))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => 1))
                .ForMember(dest => dest.DateOfBirth, opt => opt.MapFrom(src => src.DateOfBirth))
                .ForMember(dest => dest.Created, opt => opt.MapFrom(src => src.Created))
                .ForMember(dest => dest.Updated, opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role))
                .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Gender));

            CreateMap<CreateEvangelist, Evangelist>()
               .ForMember(dest => dest.Id, opt => opt.MapFrom(src => Guid.NewGuid().ToString()))
               .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName))
               .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName))
               .ForMember(dest => dest.HomeAddress, opt => opt.MapFrom(src => src.HomeAddress))
               .ForMember(dest => dest.YearsInService, opt => opt.MapFrom(src => src.YearsInService))
               .ForMember(dest => dest.PhoneNumber, opt => opt.MapFrom(src => src.PhoneNumber))
               .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.EmailAddress))
               .ForMember(dest => dest.Occupation, opt => opt.MapFrom(src => src.Occupation))
               .ForMember(dest => dest.PastorInCharge, opt => opt.MapFrom(src => src.PastorInCharge))
               .ForMember(dest => dest.StateOfOrigin, opt => opt.MapFrom(src => src.StateOfOrigin))
               .ForMember(dest => dest.Status, opt => opt.MapFrom(src => 1))
               .ForMember(dest => dest.DateOfBirth, opt => opt.MapFrom(src => src.DateOfBirth))
               .ForMember(dest => dest.Created, opt => opt.MapFrom(src => DateTime.UtcNow))
               .ForMember(dest => dest.Updated, opt => opt.MapFrom(src => DateTime.UtcNow))
               .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
               .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role))
               .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Gender));

            CreateMap<UpdateEvangelist, Evangelist>()
               .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
               .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName))
               .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName))
               .ForMember(dest => dest.HomeAddress, opt => opt.MapFrom(src => src.HomeAddress))
               .ForMember(dest => dest.YearsInService, opt => opt.MapFrom(src => src.YearsInService))
               .ForMember(dest => dest.PhoneNumber, opt => opt.MapFrom(src => src.PhoneNumber))
               .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.EmailAddress))
               .ForMember(dest => dest.Occupation, opt => opt.MapFrom(src => src.Occupation))
               .ForMember(dest => dest.PastorInCharge, opt => opt.MapFrom(src => src.PastorInCharge))
               .ForMember(dest => dest.StateOfOrigin, opt => opt.MapFrom(src => src.StateOfOrigin))
               .ForMember(dest => dest.Status, opt => opt.MapFrom(src => 1))
               .ForMember(dest => dest.DateOfBirth, opt => opt.MapFrom(src => src.DateOfBirth))
               .ForMember(dest => dest.Created, opt => opt.MapFrom(src => src.Created))
               .ForMember(dest => dest.Updated, opt => opt.MapFrom(src => DateTime.UtcNow))
               .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
               .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role))
               .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Gender));

            CreateMap<CreateUser, Members>()
              .ForMember(dest => dest.Id, opt => opt.MapFrom(src => Guid.NewGuid().ToString()))
              .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName))
              .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName))
              .ForMember(dest => dest.HomeAddress, opt => opt.MapFrom(src => src.HomeAddress))
              .ForMember(dest => dest.PhoneNumber, opt => opt.MapFrom(src => src.PhoneNumber))
              .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.EmailAddress))
              .ForMember(dest => dest.Occupation, opt => opt.MapFrom(src => src.Occupation))
              .ForMember(dest => dest.PastorInCharge, opt => opt.MapFrom(src => src.PastorInCharge))
              .ForMember(dest => dest.StateOfOrigin, opt => opt.MapFrom(src => src.StateOfOrigin))
              .ForMember(dest => dest.Status, opt => opt.MapFrom(src => 1))
              .ForMember(dest => dest.DateOfBirth, opt => opt.MapFrom(src => src.DateOfBirth))
              .ForMember(dest => dest.Created, opt => opt.MapFrom(src => DateTime.UtcNow))
              .ForMember(dest => dest.Updated, opt => opt.MapFrom(src => DateTime.UtcNow))
              .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
              .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role))
              .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Gender));

            CreateMap<UpdateUser, Members>()
              .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
              .ForMember(dest => dest.LastName, opt => opt.MapFrom(src => src.LastName))
              .ForMember(dest => dest.FirstName, opt => opt.MapFrom(src => src.FirstName))
              .ForMember(dest => dest.HomeAddress, opt => opt.MapFrom(src => src.HomeAddress))
              .ForMember(dest => dest.PhoneNumber, opt => opt.MapFrom(src => src.PhoneNumber))
              .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.EmailAddress))
              .ForMember(dest => dest.EmailConfirmed, opt => opt.MapFrom(src => src.EmailAddress.ToUpper()))
              .ForMember(dest => dest.Occupation, opt => opt.MapFrom(src => src.Occupation))
              .ForMember(dest => dest.PastorInCharge, opt => opt.MapFrom(src => src.PastorInCharge))
              .ForMember(dest => dest.StateOfOrigin, opt => opt.MapFrom(src => src.StateOfOrigin))
              .ForMember(dest => dest.Status, opt => opt.MapFrom(src => 1))
              .ForMember(dest => dest.DateOfBirth, opt => opt.MapFrom(src => src.DateOfBirth))
              .ForMember(dest => dest.Created, opt => opt.MapFrom(src => src.Created))
              .ForMember(dest => dest.Updated, opt => opt.MapFrom(src => DateTime.UtcNow))
              .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
              .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role))
              .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Gender));

            CreateMap<CreateAnnouncement, Announcement>()
              .ForMember(dest => dest.Id, opt => opt.MapFrom(src => Guid.NewGuid().ToString()))
              .ForMember(dest => dest.Status, opt => opt.MapFrom(src => 1))
              .ForMember(dest => dest.AnnouncementTitle, opt => opt.MapFrom(src => src.AnnouncementTitle))
              .ForMember(dest => dest.Created, opt => opt.MapFrom(src => DateTime.UtcNow))
              .ForMember(dest => dest.Updated, opt => opt.MapFrom(src => DateTime.UtcNow))
              .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
              .ForMember(dest => dest.AnnouncementDetail, opt => opt.MapFrom(src => src.AnnouncementDetail))
              .ForMember(dest => dest.CoverImageUrl, opt => opt.MapFrom(src => src.CoverImageUrl));

            CreateMap<UpdateAnnouncement, Announcement>()
             .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
             .ForMember(dest => dest.Status, opt => opt.MapFrom(src => 1))
             .ForMember(dest => dest.AnnouncementTitle, opt => opt.MapFrom(src => src.AnnouncementTitle))
             .ForMember(dest => dest.Created, opt => opt.MapFrom(src => src.Created))
             .ForMember(dest => dest.Updated, opt => opt.MapFrom(src => DateTime.UtcNow))
             .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
             .ForMember(dest => dest.AnnouncementDetail, opt => opt.MapFrom(src => src.AnnouncementDetail))
             .ForMember(dest => dest.CoverImageUrl, opt => opt.MapFrom(src => src.CoverImageUrl));

            CreateMap<CreateChurchActivity, ChurchActivity>()
              .ForMember(dest => dest.Id, opt => opt.MapFrom(src => Guid.NewGuid().ToString()))
              .ForMember(dest => dest.Status, opt => opt.MapFrom(src => 1))
              .ForMember(dest => dest.ActivityTime, opt => opt.MapFrom(src => src.ActivityTime))
              .ForMember(dest => dest.Created, opt => opt.MapFrom(src => DateTime.UtcNow))
              .ForMember(dest => dest.Updated, opt => opt.MapFrom(src => DateTime.UtcNow))
              .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
              .ForMember(dest => dest.ActivityDay, opt => opt.MapFrom(src => src.ActivityDay))
              .ForMember(dest => dest.ActivityName, opt => opt.MapFrom(src => src.ActivityName))
              .ForMember(dest => dest.ActivityDescription, opt => opt.MapFrom(src => src.ActivityDescription));

            CreateMap<UpdateChurchActivity, ChurchActivity>()
             .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
             .ForMember(dest => dest.Status, opt => opt.MapFrom(src => 1))
             .ForMember(dest => dest.ActivityTime, opt => opt.MapFrom(src => src.ActivityTime))
             .ForMember(dest => dest.Created, opt => opt.MapFrom(src => src.Created))
             .ForMember(dest => dest.Updated, opt => opt.MapFrom(src => DateTime.UtcNow))
             .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
             .ForMember(dest => dest.ActivityDay, opt => opt.MapFrom(src => src.ActivityDay))
             .ForMember(dest => dest.ActivityName, opt => opt.MapFrom(src => src.ActivityName))
             .ForMember(dest => dest.ActivityDescription, opt => opt.MapFrom(src => src.ActivityDescription));
        }
    }
}
